export type WallAd = { src: string; brand: string; days: number };

export const WALL_ADS: WallAd[] = [
  { src: "ads/086.jpg", brand: "Caraway", days: 10 },
  { src: "ads/076.jpg", brand: "GHIA", days: 68 },
  { src: "ads/053.jpg", brand: "Liquid Death", days: 131 },
  { src: "ads/061.jpg", brand: "Brightland", days: 46 },
  { src: "ads/091.jpg", brand: "Caraway", days: 5 },
  { src: "ads/056.jpg", brand: "Liquid Death", days: 151 },
  { src: "ads/073.jpg", brand: "Brightland", days: 54 },
  { src: "ads/094.jpg", brand: "Caraway", days: 101 },
  { src: "ads/049.jpg", brand: "Liquid Death", days: 150 },
  { src: "ads/038.jpg", brand: "Poppi", days: 17 },
  { src: "ads/028.jpg", brand: "Fishwife", days: 34 },
  { src: "ads/051.jpg", brand: "Liquid Death", days: 151 },
  { src: "ads/035.jpg", brand: "Olipop", days: 10 },
  { src: "ads/029.jpg", brand: "Fishwife", days: 17 },
  { src: "ads/055.jpg", brand: "Liquid Death", days: 151 },
  { src: "ads/009.jpg", brand: "Graza", days: 20 },
  { src: "ads/020.jpg", brand: "Fishwife", days: 34 },
  { src: "ads/054.jpg", brand: "Liquid Death", days: 27 },
  { src: "ads/065.jpg", brand: "Brightland", days: 87 },
  { src: "ads/010.jpg", brand: "Graza", days: 31 },
  { src: "ads/077.jpg", brand: "GHIA", days: 18 },
  { src: "ads/022.jpg", brand: "Fishwife", days: 34 },
  { src: "ads/040.jpg", brand: "Poppi", days: 16 },
  { src: "ads/050.jpg", brand: "Liquid Death", days: 40 },
  { src: "ads/088.jpg", brand: "Caraway", days: 77 },
  { src: "ads/002.jpg", brand: "Graza", days: 34 },
  { src: "ads/095.jpg", brand: "Caraway", days: 61 },
  { src: "ads/023.jpg", brand: "Fishwife", days: 34 },
  { src: "ads/034.jpg", brand: "Olipop", days: 10 },
  { src: "ads/090.jpg", brand: "Caraway", days: 32 },
  { src: "ads/016.jpg", brand: "Fishwife", days: 17 },
  { src: "ads/014.jpg", brand: "Graza", days: 34 },
  { src: "ads/085.jpg", brand: "Caraway", days: 100 },
  { src: "ads/078.jpg", brand: "GHIA", days: 17 },
  { src: "ads/045.jpg", brand: "Poppi", days: 37 },
  { src: "ads/092.jpg", brand: "Caraway", days: 24 },
  { src: "ads/074.jpg", brand: "GHIA", days: 89 },
  { src: "ads/044.jpg", brand: "Poppi", days: 44 },
  { src: "ads/057.jpg", brand: "Liquid Death", days: 151 },
  { src: "ads/068.jpg", brand: "Brightland", days: 101 },
  { src: "ads/006.jpg", brand: "Graza", days: 34 },
  { src: "ads/037.jpg", brand: "Olipop", days: 10 },
  { src: "ads/102.jpg", brand: "Caraway", days: 92 },
  { src: "ads/064.jpg", brand: "Brightland", days: 46 },
  { src: "ads/033.jpg", brand: "Olipop", days: 10 },
  { src: "ads/098.jpg", brand: "Caraway", days: 53 },
  { src: "ads/015.jpg", brand: "Fishwife", days: 34 },
  { src: "ads/083.jpg", brand: "GHIA", days: 61 },
  { src: "ads/046.jpg", brand: "Poppi", days: 16 },
  { src: "ads/017.jpg", brand: "Fishwife", days: 34 },
  { src: "ads/081.jpg", brand: "GHIA", days: 17 },
  { src: "ads/036.jpg", brand: "Olipop", days: 10 },
  { src: "ads/027.jpg", brand: "Fishwife", days: 34 },
  { src: "ads/070.jpg", brand: "Brightland", days: 46 },
  { src: "ads/093.jpg", brand: "Caraway", days: 4 },
  { src: "ads/018.jpg", brand: "Fishwife", days: 34 },
  { src: "ads/067.jpg", brand: "Brightland", days: 27 },
  { src: "ads/043.jpg", brand: "Poppi", days: 20 },
  { src: "ads/000.jpg", brand: "Graza", days: 37 },
  { src: "ads/032.jpg", brand: "Olipop", days: 10 },
  { src: "ads/087.jpg", brand: "Caraway", days: 32 },
  { src: "ads/041.jpg", brand: "Poppi", days: 17 },
  { src: "ads/030.jpg", brand: "Olipop", days: 10 },
  { src: "ads/026.jpg", brand: "Fishwife", days: 34 },
  { src: "ads/058.jpg", brand: "Liquid Death", days: 104 },
  { src: "ads/042.jpg", brand: "Poppi", days: 35 },
  { src: "ads/101.jpg", brand: "Caraway", days: 101 },
  { src: "ads/003.jpg", brand: "Graza", days: 114 },
  { src: "ads/031.jpg", brand: "Olipop", days: 10 },
  { src: "ads/097.jpg", brand: "Caraway", days: 32 },
  { src: "ads/004.jpg", brand: "Graza", days: 34 },
  { src: "ads/071.jpg", brand: "Brightland", days: 87 },
  { src: "ads/021.jpg", brand: "Fishwife", days: 34 },
  { src: "ads/007.jpg", brand: "Graza", days: 45 },
  { src: "ads/089.jpg", brand: "Caraway", days: 101 },
  { src: "ads/052.jpg", brand: "Liquid Death", days: 107 },
  { src: "ads/008.jpg", brand: "Graza", days: 54 },
  { src: "ads/080.jpg", brand: "GHIA", days: 74 },
  { src: "ads/072.jpg", brand: "Brightland", days: 101 },
  { src: "ads/001.jpg", brand: "Graza", days: 17 },
  { src: "ads/019.jpg", brand: "Fishwife", days: 33 },
  { src: "ads/039.jpg", brand: "Poppi", days: 17 },
  { src: "ads/005.jpg", brand: "Graza", days: 34 },
  { src: "ads/100.jpg", brand: "Caraway", days: 101 },
  { src: "ads/082.jpg", brand: "GHIA", days: 18 },
  { src: "ads/011.jpg", brand: "Graza", days: 34 },
  { src: "ads/096.jpg", brand: "Caraway", days: 23 },
  { src: "ads/084.jpg", brand: "GHIA", days: 34 },
  { src: "ads/012.jpg", brand: "Graza", days: 11 },
  { src: "ads/063.jpg", brand: "Brightland", days: 87 },
  { src: "ads/099.jpg", brand: "Caraway", days: 53 },
  { src: "ads/024.jpg", brand: "Fishwife", days: 34 },
  { src: "ads/079.jpg", brand: "GHIA", days: 74 },
  { src: "ads/069.jpg", brand: "Brightland", days: 44 },
  { src: "ads/025.jpg", brand: "Fishwife", days: 17 },
  { src: "ads/103.jpg", brand: "Caraway", days: 4 },
  { src: "ads/062.jpg", brand: "Brightland", days: 46 },
  { src: "ads/075.jpg", brand: "GHIA", days: 89 },
  { src: "ads/060.jpg", brand: "Liquid Death", days: 122 },
];
