import { Creative } from "./types";

export const CREATIVES: Creative[] = [
  {
    id: "c1",
    title: "Cabin Season — hero pour",
    size: "1024x1280",
    aspect: "4 / 5",
    image: "creatives/lib-01.jpg",
    pos: "60% 50%",
    status: "completed",
  },
  {
    id: "c2",
    title: "Amber & Ash — story frame",
    size: "1024x1024",
    aspect: "1 / 1",
    image: "creatives/lib-02.jpg",
    pos: "50% 50%",
    status: "completed",
  },
  {
    id: "c3",
    title: "Gift trio — square offer",
    size: "1088x1920",
    aspect: "9 / 16",
    image: "creatives/lib-03.jpg",
    pos: "70% 50%",
    status: "completed",
  },
  {
    id: "c4",
    title: "Clean burn — ingredient proof",
    size: "1024x1280",
    aspect: "4 / 5",
    image: "creatives/lib-04.jpg",
    pos: "50% 40%",
    status: "completed",
  },
  {
    id: "c5",
    title: "Bold / Punchy",
    size: "1024x1024",
    aspect: "1 / 1",
    image: "creatives/lib-05.jpg",
    pos: "50% 50%",
    status: "completed",
  },
  {
    id: "c6",
    title: "Subscribe & save — retargeting",
    size: "1024x1280",
    aspect: "4 / 5",
    image: "creatives/lib-07.jpg",
    pos: "28% 50%",
    status: "completed",
  },
  {
    id: "c7",
    title: "60-hour burn — value math",
    size: "1088x1920",
    aspect: "9 / 16",
    image: "creatives/lib-08.jpg",
    pos: "35% 50%",
    status: "completed",
  },
  {
    id: "c8",
    title: "Lifestyle / Photo-real",
    size: "1024x1024",
    aspect: "1 / 1",
    image: "creatives/lib-06.jpg",
    pos: "50% 50%",
    status: "completed",
  },
  {
    id: "c9",
    title: "Founder story — small batch",
    size: "1024x1280",
    aspect: "4 / 5",
    image: "creatives/lib-09.jpg",
    pos: "72% 50%",
    status: "completed",
  },
  {
    id: "c10",
    title: "Holiday teaser — early access",
    size: "1024x1024",
    aspect: "1 / 1",
    image: "creatives/lib-10.jpg",
    pos: "28% 50%",
    status: "completed",
  },
  {
    id: "c11",
    title: "Clean / Minimal",
    size: "1024x1280",
    aspect: "4 / 5",
    status: "generating",
  },
  {
    id: "c12",
    title: "Cart abandoners — 14 day",
    size: "1024x1280",
    aspect: "4 / 5",
    status: "failed",
  },
];

export const CREATIVES_PAGES = ["1", "2", "3"];

export const CREATIVES_COLUMN_COUNT = 5;
