export type RingCard =
  | { kind: "img"; file: string; w: number; h: number }
  | { kind: "disc"; a: string; b: string; c: string }
  | { kind: "pill"; label: string }
  | { kind: "list" }
  | { kind: "chips" };

export const RING_CARDS: readonly RingCard[] = [
  { kind: "img", file: "ad-templates/baxter-of-california_top-1-9d.jpg", w: 230, h: 152 },
  { kind: "img", file: "ad-templates/baxter-of-california_top-3-5d.jpg", w: 230, h: 152 },
  { kind: "img", file: "ad-templates/baxter-of-california_top-4-5d.jpg", w: 230, h: 152 },
  { kind: "pill", label: "Generate script" },
  { kind: "img", file: "ad-templates/beyond-meat_top-2-45d.jpg", w: 230, h: 152 },
  { kind: "img", file: "ad-templates/blueland_top-2-43d.jpg", w: 230, h: 152 },
  { kind: "img", file: "ad-templates/branch-basics_top-2-136d.jpg", w: 230, h: 152 },
  { kind: "disc", a: "#f6f0b0", b: "#4ec3c9", c: "#1a2a9c" },
  { kind: "img", file: "ad-templates/caraway_top-7-52d.jpg", w: 230, h: 152 },
  { kind: "img", file: "ad-templates/crown-affair_top-7-8d.jpg", w: 230, h: 152 },
  { kind: "img", file: "ad-templates/crown-affair_top-8-7d.jpg", w: 230, h: 152 },
  { kind: "pill", label: "Generate script" },
  { kind: "img", file: "ad-templates/crown-affair_top-9-3d.jpg", w: 230, h: 152 },
  { kind: "img", file: "ad-templates/dandelion-chocolate_top-1-55d.jpg", w: 230, h: 152 },
  { kind: "list" },
  { kind: "img", file: "ad-templates/dandelion-chocolate_top-2-55d.jpg", w: 230, h: 152 },
  { kind: "disc", a: "#ff4d2e", b: "#c0181a", c: "#5a0a1a" },
  { kind: "img", file: "ad-templates/dollar-shave-club_top-8-17d.jpg", w: 230, h: 152 },
  { kind: "img", file: "ad-templates/fr-ya-organics_top-6-338d.jpg", w: 230, h: 152 },
  { kind: "img", file: "ad-templates/mejuri_top-5-79d.jpg", w: 230, h: 152 },
  { kind: "pill", label: "Generate script" },
  { kind: "img", file: "ad-templates/momofuku-goods_top-2-79d.jpg", w: 230, h: 152 },
  { kind: "img", file: "ad-templates/purple_top-10-4d.jpg", w: 230, h: 152 },
  { kind: "img", file: "ad-templates/salt-stone_top-5-135d.jpg", w: 230, h: 152 },
  { kind: "disc", a: "#d9f0c0", b: "#5aa0ff", c: "#2b1d80" },
  { kind: "img", file: "creative-wall/atoms_top-9-1d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/baxter-of-california_top-1-9d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/beehiiv_top-5-39d.jpg", w: 230, h: 152 },
  { kind: "pill", label: "Generate script" },
  { kind: "img", file: "creative-wall/blickpunkt-vital-gesundheitstipps_top-3-82d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/cari-nutrition_top-4-93d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/coinbase_top-s5.jpg", w: 230, h: 152 },
  { kind: "disc", a: "#fff1a8", b: "#f0a030", c: "#3b2a10" },
  { kind: "img", file: "creative-wall/deel_top-9-17d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/dog-is-human_top-3-73d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/dr-luisa-neumann_top-7-26d.jpg", w: 230, h: 152 },
  { kind: "pill", label: "Generate script" },
  { kind: "img", file: "creative-wall/einhornstaub_top-1-230d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/elara-care_top-4-11d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/fr-ya-organics_top-5-410d.jpg", w: 230, h: 152 },
  { kind: "disc", a: "#c8f5e0", b: "#20a080", c: "#0b3a30" },
  { kind: "img", file: "creative-wall/gainful_top-1-110d.jpg", w: 230, h: 152 },
  { kind: "chips" },
  { kind: "img", file: "creative-wall/grammarly_top-1-87d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/gusto_top-4-91d.jpg", w: 230, h: 152 },
  { kind: "pill", label: "Generate script" },
  { kind: "img", file: "creative-wall/harry-s_top-8-45d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/inno-supps-night-shred_top-10-31d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/intercom_top-5-4d.jpg", w: 230, h: 152 },
  { kind: "disc", a: "#ffd6e8", b: "#e0409a", c: "#3a0c30" },
  { kind: "img", file: "creative-wall/lanuvi-magazine_top-2-178d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/lanuvi-magazine_top-4-162d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/lanuvi-magazine_top-6-159d.jpg", w: 230, h: 152 },
  { kind: "pill", label: "Generate script" },
  { kind: "img", file: "creative-wall/mejuri_top-4-79d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/miye_top-10-79d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/n-cessaire_top-5-59d.jpg", w: 230, h: 152 },
  { kind: "disc", a: "#e8f5a0", b: "#37c3c0", c: "#102060" },
  { kind: "img", file: "creative-wall/notion_top-3-52d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/nubank_top-9-38d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/on_top-7-43d.jpg", w: 230, h: 152 },
  { kind: "pill", label: "Generate script" },
  { kind: "img", file: "creative-wall/priority-bicycles_top-9-36d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/ritual_top-10-111d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/ritual_top-6-116d.jpg", w: 230, h: 152 },
  { kind: "disc", a: "#f6f0b0", b: "#4ec3c9", c: "#1a2a9c" },
  { kind: "img", file: "creative-wall/silver-fern-brand_top-3-310d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/tracksmith_top-6-50d.jpg", w: 230, h: 152 },
  { kind: "img", file: "creative-wall/vet-s-daily-care_top-10-3d.jpg", w: 230, h: 152 },
  { kind: "pill", label: "Generate script" },
  { kind: "img", file: "creative-wall/zero-motorcycles_top-7-36d.jpg", w: 230, h: 152 },
];

export const PLATE_BG = ["ad-templates/salt-stone_top-2-135d.jpg", "ad-templates/crown-affair_top-1-11d.jpg"] as const;

export const MOSAIC_TILES = [
  { file: "apps/synthesia_top-1-18d.jpg", x: 40, y: 0, w: 600, h: 590, echo: { dx: -70, dy: 0 } },
  { file: "creative-wall/gravity_top-2-69d.jpg", x: 680, y: 0, w: 570, h: 440, echo: { dx: 40, dy: -40 } },
  { file: "apps/nanit_top-3-4d.jpg", x: 1310, y: 120, w: 590, h: 700, echo: { dx: 60, dy: 40 } },
  { file: "creative-wall/coinbase_top-s5.jpg", x: 290, y: 600, w: 710, h: 480, echo: { dx: 0, dy: 40 } },
] as const;

export const FAN_CARDS = [
  "apps/akiflow_top-1-73d.jpg",
  "apps/wispr-flow_top-s1-23d.jpg",
  "apps/base44_top-2-43d.jpg",
  "apps/heygen_top-2-42d.jpg",
  "apps/cluely_top-4-11d.jpg",
  "ad-templates/salt-stone_top-5-135d.jpg",
  "apps/granola_top-2-30d.jpg",
  "apps/whoop_top-1-53d.jpg",
  "apps/rocket-money_top-s8.jpg",
  "ad-templates/crown-affair_top-7-8d.jpg",
  "apps/starface_top-8-30d.jpg",
  "apps/todoist_top-1-6d.jpg",
  "ad-templates/casper_top-1-17d.jpg",
  "apps/owlet_top-2-6d.jpg",
  "ad-templates/blueland_top-1-78d.jpg",
  "ad-templates/helix_top-1-201d.jpg",
  "apps/cleo_top-2-45d.jpg",
  "ad-templates/p-f-candle-co_top-1-57d.jpg",
  "ad-templates/dollar-shave-club_top-2-62d.jpg",
  "ad-templates/branch-basics_top-2-136d.jpg",
  "apps/capcut_top-10-89d.jpg",
  "apps/chime_top-s10.jpg",
  "apps/nanit_top-2-23d.jpg",
  "ad-templates/otherland_top-2-107d.jpg",
  "ad-templates/caraway_top-10-47d.jpg",
  "apps/cursor_top-3-2d.jpg",
] as const;

export type GridTile =
  | { kind: "img"; file: string }
  | { kind: "disc"; a: string; b: string; c: string }
  | { kind: "text"; text: string; color?: string; size?: number; weight?: number; italic?: boolean; serif?: boolean; tracking?: string };

const sq = (file: string): GridTile => ({ kind: "img", file });

export const CHARACTER_TILES: readonly GridTile[] = [
  sq("creative-wall/aimoji-ai-stickers-keyboard_top-2-53d.jpg"),
  sq("creative-wall/baxter-of-california_top-1-9d.jpg"),
  sq("creative-wall/blickpunkt-vital-gesundheitstipps_top-3-82d.jpg"),
  sq("creative-wall/coinbase_top-s5.jpg"),
  sq("creative-wall/dr-luisa-neumann_top-10-26d.jpg"),
  sq("creative-wall/evolv_top-4-44d.jpg"),
  sq("creative-wall/gravity_top-2-69d.jpg"),
  sq("creative-wall/instantly_top-8-18d.jpg"),
  sq("creative-wall/lanuvi-magazine_top-1-193d.jpg"),
  sq("apps/starface_top-8-30d.jpg"),
  sq("creative-wall/momofuku-goods_top-2-79d.jpg"),
  sq("creative-wall/novo-nordisk_top-4-89d.jpg"),
  sq("creative-wall/purina-pro-plan-vet_top-3-16d.jpg"),
  sq("creative-wall/sofi_top-1-153d.jpg"),
  sq("ad-templates/crown-affair_top-10-2d.jpg"),
  sq("ad-templates/dandelion-chocolate_top-2-55d.jpg"),
  sq("ad-templates/atoms_top-5-6d.jpg"),
  sq("ad-templates/fr-ya-organics_top-6-338d.jpg"),
  sq("creative-wall/loftie_top-6-52d.jpg"),
  sq("apps/chime_top-4-10d.jpg"),
  sq("apps/heygen_top-4-42d.jpg"),
  sq("ad-templates/salt-stone_top-10-38d.jpg"),
  sq("ad-templates/baxter-of-california_top-3-5d.jpg"),
  sq("ad-templates/caraway_top-7-52d.jpg"),
];

const disc = (a: string, b: string, c: string): GridTile => ({ kind: "disc", a, b, c });
const txt = (text: string, o: Partial<Extract<GridTile, { kind: "text" }>> = {}): GridTile => ({ kind: "text", text, ...o });

export const MUSIC_TILES: readonly GridTile[] = [
  txt("just like this", { color: "#9AA", size: 40 }),
  disc("#f6f0b0", "#e8603a", "#3b1030"),
  disc("#ffd6e8", "#8a5cff", "#1a1a5a"),
  txt("studio", { color: "#C4161C", size: 62, weight: 900 }),
  disc("#e8f5a0", "#37c3c0", "#102060"),
  txt("feeling\nis the reward for starting", { color: "#8FB4FF", size: 34 }),
  txt("Can do\nit", { serif: true, weight: 400, size: 60, color: "#DADADA" }),
  disc("#c8f5e0", "#2a80ff", "#0b1a50"),
  disc("#fff1a8", "#f0a030", "#3b2a10"),
  txt("one\nswipe\nthat's\nit\ngrab", { size: 40, color: "#CFCFCF" }),
  disc("#ffd6e8", "#e0409a", "#3a0c30"),
  disc("#d9f0c0", "#5aa0ff", "#2b1d80"),
  txt("HEY THERE,", { italic: true, size: 40, color: "#6E9BFF" }),
  txt("hey there", { weight: 400, size: 44, color: "#BBB" }),
  disc("#f6f0b0", "#4ec3c9", "#1a2a9c"),
  txt("TEAMS\nLOSE", { size: 50, weight: 900, color: "#E0C23A" }),
  disc("#ff4d2e", "#c0181a", "#5a0a1a"),
  txt("just like this", { weight: 400, size: 40, color: "#DDD" }),
  txt("lack of", { serif: true, size: 56, color: "#D0362F" }),
  disc("#c8f5e0", "#20a080", "#0b3a30"),
  txt("feeling", { size: 46, color: "#8FB4FF" }),
  disc("#fff1a8", "#f0a030", "#3b2a10"),
  txt("swipe", { size: 58, weight: 900, color: "#CFCFCF" }),
  disc("#e8f5a0", "#37c3c0", "#102060"),
];

export const SUBTITLE_TILES: readonly GridTile[] = [
  txt("just like this", { size: 40, color: "#C9C9C9" }),
  txt("bought\nit Verdict:", { serif: true, italic: true, weight: 400, size: 48, color: "#D8D8D8" }),
  txt("just like this", { weight: 400, size: 42, color: "#E6E6E6" }),
  txt("studio\nis officially open", { color: "#C4161C", size: 54, weight: 900 }),
  txt("usual", { serif: true, weight: 700, size: 60, color: "#C9C63A" }),
  txt("feeling\nis the reward for starting", { size: 34, color: "#8FB4FF" }),
  txt("Can do\nit", { serif: true, weight: 400, size: 60, color: "#DADADA" }),
  txt("one\nswipe\nthat's\nit\ngrab", { size: 40, color: "#CFCFCF" }),
  txt("just like this", { size: 30, color: "#A6FF00", tracking: "0.02em" }),
  txt("just like this", { serif: true, italic: true, weight: 400, size: 44, color: "#E3E3E3" }),
  txt("just like this", { size: 40, color: "#F5D20B" }),
  txt("I kept\nputting", { serif: true, italic: true, weight: 400, size: 46, color: "#E0C23A" }),
  txt("HEY THERE,", { italic: true, size: 40, color: "#6E9BFF" }),
  txt("hey there", { weight: 400, size: 44, color: "#BBB" }),
  txt("I kept", { serif: true, italic: true, weight: 400, size: 48, color: "#DDD" }),
  txt("TEAMS\nLOSE", { size: 50, weight: 900, color: "#E0C23A" }),
  txt("Marketing\nweeks", { serif: true, italic: true, weight: 400, size: 40, color: "#EEE" }),
  txt("just like this", { weight: 400, size: 40, color: "#DDD" }),
  txt("lack of", { serif: true, size: 56, color: "#D0362F" }),
  txt("feeling", { size: 46, color: "#8FB4FF" }),
  txt("Can do", { serif: true, weight: 400, size: 56, color: "#DADADA" }),
  txt("swipe", { size: 58, weight: 900, color: "#CFCFCF" }),
  txt("I kept", { serif: true, italic: true, weight: 400, size: 48, color: "#DDD" }),
  txt("just like this", { size: 40, color: "#C9C9C9" }),
];

export const CLONE_FILES = [
  "creative-wall/beehiiv_top-5-39d.jpg",
  "creative-wall/on_top-7-43d.jpg",
  "ad-templates/crown-affair_top-1-11d.jpg",
  "creative-wall/coinbase_top-s5.jpg",
  "ad-templates/salt-stone_top-2-135d.jpg",
  "creative-wall/beehiiv_top-5-39d.jpg",
  "ad-templates/crown-affair_top-1-11d.jpg",
  "creative-wall/on_top-7-43d.jpg",
  "creative-wall/coinbase_top-s5.jpg",
  "ad-templates/casper_top-1-17d.jpg",
  "creative-wall/beehiiv_top-5-39d.jpg",
  "ad-templates/crown-affair_top-1-11d.jpg",
] as const;
